# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Black Duck Security Action allows you to integrate Static Analysis Security Testing (SAST) and Software Composition Analysis (SCA) into your CI/CD pipelines.
# For more information about configuring your workflow,
# read our documentation at https://github.com/blackduck-inc/black-duck-security-scan

name: Coverity Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '23 10 * * 0'

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      actions: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Black Duck Coverity scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          bridgecli_download_url: "https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/3.9.2rc1/bridge-cli-bundle-3.9.2rc1-win64.zip"
          ### ---------- COVERITY SCANNING: REQUIRED FIELDS ----------
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_project_name: 'WebGoat-Jie'
          coverity_stream_name: 'WebGoat-Jie'
          #coverity_version: '2025.6'
          ### GITHUB TOKEN
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Required when PR comments or sarif reports enabled
          coverity_prComment_enabled: true
          coverity_prComment_impacts: 'High,Medium,Low'

          ### POLICY ENFORCEMENT: to break the build
          coverity_policy_view: "Outstanding Issues"
          #coverity_policy_view: '10010'

          ### Arbitrary Parameters
          #coverity_build_command: mvn install
          #coverity_clean_command: mvn clean
          
          ### LOCAL ANALYSIS: Uncomment below to enable
          # coverity_local: false # Enable local analysis mode

          ### SCAN CONFIGURATION: Uncomment below to enable
          #coverity_waitForScan: true # Wait for scan completion before proceeding

          ### Mark build status if policy violating issues are found
          #mark_build_status: failure # Set to success, failure, or skip

          ### Uncomment below configuration if Bridge diagnostic files needs to be uploaded
          # include_diagnostics: false
         
