# Quickstart: Black Duck Security Scan Action with polaris:
#     /bundle/bridge/page/documentation/t_github-polaris-quickstart.html
name: Polaris Security Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}
# GitHub token permissions for post-scan actions. Required for built-in GITHUB_TOKEN; if using a PAT with equivalent scopes, permissions block can be commented out.
permissions:
  contents: write               # Enables pushing commits and creating fix branches
  pull-requests: write          # Allows commenting on and creating pull requests
  security-events: write        # Permits uploading SARIF results to GitHub Security
jobs:
  polaris:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Polaris Security Scan
        id: polaris-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_POC_URL }}
          polaris_access_token: ${{ secrets.POLARIS_POC_ACCESS_TOKEN }}
          ### ASSESSMENT TYPES
          polaris_assessment_types: SCA,SAST  # Comma-separated list: SAST,SCA,DAST
          ### GITHUB TOKEN
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Required when PR comments or sarif reports enabled
          polaris_prComment_enabled: true
          # polaris_prComment_severities: "Critical,High,Low"
          ### SARIF report parameters
          polaris_reports_sarif_create: true  # Create SARIF report and upload it as artifact
          polaris_upload_sarif_report: true  # Upload SARIF report in GitHub Advanced Security tab
          polaris_reports_sarif_groupSCAIssues: true
          polaris_reports_sarif_issue_types: "SAST, SCA"


          ### SCAN CONFIGURATION: Uncomment below to enable
          # polaris_waitForScan: true # Wait for scan completion before proceeding

          ### Mark build status if policy violating issues are found
          mark_build_status: failure # Set to success, failure, or skip

          ### Uncomment below configuration if Bridge diagnostic files needs to be uploaded
          include_diagnostics: true
